### ISSUE TITLE
Izzy Repo

### ISSUE THREAD

**Issue by mamasch19** [adil192/saber#146]
If I remember correctly, the app used to be on the IzzyOnDroid repo, I only just now realized it's not anymore. 

I usually like to install and update my apps through IzzyOnDroid repo if given the choice, since updates come out faster there and it has the same signature as the GitHub releases, leaving me the option to update manually if needed.

That brings the question: Is this a decision made on purpose now that it's in cluded in the official F-Droid Repo?

**Comment by adil192** [comment]
> https://apt.izzysoft.de/fdroid/index/info:
> Another reason for an app getting removed from my repo is if it was added to the „official F-Droid repository“. Removal then mainly is to avoid confusion at the users' end, due to signature mismatch on updates (if they installed an app from the official repo, signed with F-Droid's key, and an update rolls in earlier via my repo – which is usually the case – there'd be a warning displayed if they'd try to apply that update).
> In some cases an app still stays with my repo; usually it then uses [reproducible builds](https://f-droid.org/en/docs/Reproducible_Builds/) so there'd be no signature mismatch.

It seems this was intentional by IzzyOnDroid. I'll see if I can do anything about providing reproducible builds

**Comment by adil192** [comment]
Providing reproducible builds won't be possible because of the tweaks needed when publishing to F-Droid (i.e. `flutter build apk` vs [`flutter build apk -t lib/main_fdroid.dart`](https://github.com/adil192/saber/blob/main/lib/main_fdroid.dart)). 
Also it seems that (currently) enabling this feature means I'd have to turn off the F-Droid self-updating mechanism and submit a pull request each update.
