### ISSUE TITLE
Allow generic webdav as a sync backend

### ISSUE THREAD

**Issue by dbrandonjohnson** [adil192/saber#201]
Implementing generic webdav would enable syncing with other syncing solutions including Seafile.

**Comment by adil192** [comment]
There are no current plans to use generic webdav since none of the WebDav functionality is implemented in Saber directly, but in the [Nextcloud plugin](https://github.com/provokateurin/nextcloud-neon/tree/main/packages/nextcloud). You could file an issue there but imo I doubt it'd be implemented.

**Comment by PulsarFX** [comment]
@adil192 does this PR add the required changes to support generic WebDav?

**Comment by adil192** [comment]
> [nextcloud/neon#190](https://github.com/nextcloud/neon/pull/190)

That's just adding support for Flutter web apps

**Comment by docentYT** [comment]
It's sad that WebDAV isn't supported. I have a Synology file server and don't see the need to run a heavy Nextcloud server.

**Comment by alfureu** [comment]
Hm, just landed on this page, as I was looking for a WebDAV sync option. Using OwnCloud (a _de facto_ fork of NextCloud) as many cannot run NextCloud for a number of reasons, and it is a **shame** WebDAV is/will not be supported. I suspect I need to look for another app then...

**Comment by adil192** [comment]
WebDAV without Nextcloud *cannot* be supported. The infrastructure for it doesn't exist. I've yet to see a WebDav package on pub.dev that's actually maintained.

To anyone reading this, please refrain from "I also want this" comments unless you're offering a way forward.

**Comment by germanocorrea** [comment]
For anyone interested: I realized there might be a workaround without implementing webdav support. @adil192 if this is out of place, I can take my comment elsewhere, but I realized this issue is a good place since people come here expecting a way to use generic webdav with saber.

I just installed saber, so I'm still exploring the app.

I'm currently using the open source app "DAVx5" to mount a webdav folder I have on a server in my android phone. I was able to select this folder as Saber's custom directory (I don't know this config name in english because my app is in portuguese). Only issue is it seems I have a file permission misconfiguration on my server, so notes aren't saving, but I think this is easily solvable.

Later this weekend I plan on fixing this permission issue, will come back if everything works fine.

DAVx5 is free on F-Droid.
