### ISSUE TITLE
Build Android app on GitHub Actions

### ISSUE THREAD

**Issue by Sdarfeesh** [adil192/saber#30]
Is it able to build Saber for Android on GitHub Actions?
So people can get the newest version in a short time

**Comment by adil192** [comment]
I'm not sure if this is possible without sharing the signing certificate publicly

**Comment by adil192** [comment]
Turns out it would be possible with something like [android-sign](https://github.com/marketplace/actions/android-sign) but I'm not sure what problem this would solve: I would still be the only person able to run signed builds.
I don't think nightlies would be a good fit for this project as it would eat through my GitHub Actions minutes and also I release relatively quickly anyway.
