### ISSUE TITLE
Cannot cover the paints with white color

### ISSUE THREAD

**Issue by Sdarfeesh** [adil192/saber#332]
**Describe the bug**
Drawn paints cant be covered by white color

**To Reproduce**
1. Draw with any color except white
2. Try to cover it with white color

**Expected behavior**
Paint can be covered by white color

**Screenshots**

https://user-images.githubusercontent.com/50188628/218249838-70d04e53-5b72-4f6b-bfec-b18f25768574.mp4

**Device (please complete the following information):**
 - Device: Alldocube iPlay 20
 - OS: Android 10
 - Version: v0.9.1

**Comment by adil192** [comment]
I'm not sure what you mean by paints. Also the screen recording isn't working, please can you re-upload?

**Comment by fybx** [comment]
@adil192 I followed the steps @Sdarfeesh gave, and it turns out that any colour except white can be stacked correctly.

1. Select the pen tool
2. Select any colour (ex. blue)
3. Draw a circle
4. Select another colour (ex. red)
5. You can divide the blue circle into two using the red line since it's on top
6. Select white colour
7. Draw another line, cutting the red
8. White line is sent to back

I will add a screen recording as soon as I can

**Comment by adil192** [comment]
This happened because the strokes were sorted by color which was required for allowing highlighter strokes to overlap. I've changed it so that only highlighter strokes are sorted by color.
