### ISSUE TITLE
Unable to access notes after leaving the app

### ISSUE THREAD

**Issue by WasteOfO2** [adil192/saber#424]
**Describe the bug**

After creating a file and exiting the app, you can no longer access the file from the home page, but accessible via the side panel

**To Reproduce**
1. Create a new note
2. Make some changes (say load an image) to the note
3. Exit the app

**Expected behavior**

Expected to be able to access my notes after leaving the app

**Screenshots**

![Screenshot_20230227-064053_Saber](https://user-images.githubusercontent.com/45941793/221450527-d2d64f23-6175-40ea-94f6-a73e8f0dfc41.png)

**Device (please complete the following information):**
 - Device: Samsung Galaxy Tab S6 Lite LTE
 - OS: Lineage OS 19-20230121-NIGHTLY-gta4xl
 - Version: v.0.9.5 (Saber FOSS)
 - Browser (if applicable): -

Will keep updating this issue until I am able to reproduce this more consistently and provide more info

**Comment by WasteOfO2** [comment]
This only seems to be a one off case, subsequent documents seem to load fine

**Comment by adil192** [comment]
This should be fixed with https://github.com/adil192/saber/commit/bed50b80ee730b9e7ef3733c5e7dbb36a1db3cfb. Feel free to reopen if not

**Comment by m0byn** [comment]
I am having the same problem right now. 

Describe the bug

I imported an image and closed the note, and afterwards the complete app. When reopened, it looked like the screenshot above. Fully closing and reopening the app and restarting the tablet did not help.

To Reproduce
Steps to reproduce the behavior:

Open new note
Import Image
Leave note
Voila, long grey stripe showing in tab "last notes"
Cannot reopen the mentioned notes

Expected behavior

Expected to be able to access my notes after leaving the app

Device (please complete the following information):

    Device: Samsung Galaxy Tab S4 LTE (SM-T835)
    OS: Android 10, Samsung One UI-Version 2.1
    Version: v.0.9.5 (Google Play)
    Browser (if applicable): -

**Comment by WasteOfO2** [comment]
Download This APK from the GH Actions page until a new release is made

https://github.com/adil192/saber/suites/11223574848/artifacts/574395663
