### ISSUE TITLE
Sync does not download larger notes (e.g. ≥ 1.2 MB) properly

### ISSUE THREAD

**Issue by Iey4iej3** [adil192/saber#780]
### Describe the bug

I login the account from another (empty) device and try to download the notes from Sync. The spin rotates but nothing successfully downloaded. I tried to remove the Saber folder, but failed on the server. I then deleted the account, created a new account, and synchronized, but still, I cannot download from the empty device.

I looked at the network capture, and saw that the app has downloaded several files (more precisely, several chunks of some megabytes), but the notes are not shown (I tried to restart, and even clean the user data to retry, but without success).

### To reproduce

1. Install Saber on a new device (or clean the user data);
2. Login to sync;
3. (Notes are not shown, then) restart Saber.

### Expected behavior

All notes are correctly downloaded

### Saber version

v0.14.2 (F-Droid)

### Device

- Device: Samsung S6 Lite; Xiaomi 11 Lite
- OS: LineageOS 20 (Android 13)

### Anything else?

This happens only this week. It is probable that this is a newly introduced bug, and it is possibly related to the new feature of creating folders (I have created folders since then).

**Comment by adil192** [comment]
Are you using a custom Nextcloud server that's not on Nextcloud 27?

**Comment by Iey4iej3** [comment]
I am using the default (i.e. your) server.

**Comment by Iey4iej3** [comment]
Let me mention that, on my computer with the flatpak build, after a synchronization, some notes are downloaded (but not all). I also checked that, on the server, the number of `sbe` files is correct (i.e. precisely how many notes that I have).

**Comment by relink2013** [comment]
Im having a similar experience so I thought I'd comment here instead of opening a new issue. 

- I'm using the latest Apple Appstore  release v0.14.6
- Nextcloud v27.0.0 
- Using a subdomain eg. nc.domain.com
- Running my own NC server.
    - NGINX
    - PHP 8.1
    - PostgreSQL
    - Redis
    

I have Saber installed on my iPad, iPhone, and MacBookPro. 

All 3 devices are completely out of sync with each-other.

- The iPad is the only one that has all my notes on it, likely because most of the notes were created on it.

- The iPhone and MacBook both refuse to sync over most of my notes, and they few they did sync are out of date.

Despite this any time I create a note on any device I can see the file being created and updated within seconds on NC.

Im not sure what's causing the issue and I don't see anywhere in the app to view any kind of Logs.

**Comment by kb3uyi** [comment]
I'm having the same experience on 2 android devices (pixel 6 pro android 13, samsung tab s6 lite).

My nextcloud server is on a subfolder like:
 HTTPS://[user subdomain].duckdns.org/nextcloud/
 
 It's on a pi4 running ubuntu server, with nextcloud and apache installed as packages (not the docker container).
 
 If anyone has advice i'd be willing to change the apache settings:
 
  /etc/apache2/sites-enabled/nextcloud-le-ssl.conf   

```
<IfModule mod_ssl.c>

Alias /nextcloud "/var/www/html/nextcloud/"

<VirtualHost *:80>
        ServerName snoozyfiles.duckdns.org
        # Redirect permanent / https://XXXXXXX.duckdns.org/
        # ^ broken. recursive!
        RedirectMatch ^/$ /nextcloud/
</VirtualHost>

<VirtualHost *:443>
    DocumentRoot "/var/www/html/nextcloud"
    ServerName snoozyfiles.duckdns.org
    Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"

    <Directory "/var/www/html/nextcloud/">
        Options MultiViews FollowSymlinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>

        TransferLog /var/log/apache2/nextcloud_access.log
        ErrorLog /var/log/apache2/nextcloud_error.log
</VirtualHost>
</IfModule>
```

This is beheind an NGINX proxy on another Pi. Maybe later I can try spinning up the container version of nextcloud on the webserver root, or change the apache settings to put this one at root.

**Comment by kb3uyi** [comment]
OK, since yesterday I have updated nextcloud from 27, to 27.0.1. And I have changed the alias in sites-enabled from "/nextcloud" to "/" to force it to be on the root of the webserver and not have "/nextcloud" in the URL.

That didn't resolve it so I also deleted the Saber folder on nextcloud. I readded it on my phone and then force quit and restarted the application. 

Then I force quit and readded on my tablet. The notes from the phone are now on the tablet, but not the other way around. 
New notes from either device would be copied, but I was using a pen on my tablet to take notes om something for a tabletop game and that refused to copy. It was in a folder so I moved it to root. N o such luck.

New notes copy and I see that on my phone. So i probably should have removed the saber folder and then promptly used the tablet instead of the phone. 

Either way, it looks like syncing is broken if the nextcloud URL is not right at the root.

**Comment by Iey4iej3** [comment]
@adil192 It seems to me that, as long as the file is larger than 1MB (not sure whether it is exact), the file cannot be correctly downloaded.

I performed a random drawing (it is not a tarball, but compressed by gzip):
[large.sbn.gz](https://github.com/adil192/saber/files/12210513/large.sbn.gz)

It seems that the file uploads successfully, but it cannot be correctly downloaded.

**Comment by Iey4iej3** [comment]
@kb3uyi If I understand correctly, please repost your issue under https://github.com/adil192/saber/issues/772 which addresses precisely the subfolder issue.

**Comment by kb3uyi** [comment]
> @kb3uyi If I understand correctly, please repost your issue under #772 which addresses precisely the subfolder issue.

Will do. Thanks!
